### ISSUE TITLE
Storage: GB Capacity 

### ISSUE THREAD

**Issue by AlpineEdward** [Sienna7002/Specifier#2]
![PXL_20221229_230959557.jpg](https://user-images.githubusercontent.com/109859312/210019716-648b7137-dcc2-4db3-b52a-ec7a705d374b.jpg)

**Comment by Sienna7002** [comment]
Most likely the Snow Leopard not co-operating

**Comment by Sienna7002** [comment]
The issue is caused by the command not being recognised by snow leopard, so it's a operating system problem and not with specifier.
